/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectakhir.MainFrame;

import controller.koneksi;
import java.awt.Color;
import java.awt.Component;
import java.awt.HeadlessException;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.HashMap;
import java.util.concurrent.TimeUnit;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import projectakhir.FrontView;

/**
 *
 * @author macbookpro
 */
public final class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private ResultSet rs;
    private Statement st;
    private PreparedStatement ps;
    Connection conn = koneksi.Koneksi();
    String id_user="0", username="0", email="0", nim="0", nohp="0", password="0", role="0";
    String id_buku="0", tglhari_ini = "0", id_trans = "0", tgl_tenggat = "00-00-0000", tgl_tenggat_lama = "00-00-0000";;
    long denda = 0, selisihTenggat = 0;
    DefaultTableModel model = new DefaultTableModel();
    DefaultTableModel modelpinjam = new DefaultTableModel();
    DefaultTableModel modelpinjamdiperpanjangan = new DefaultTableModel();
    DefaultTableModel modelhistory = new DefaultTableModel();
    DefaultTableModel modelstatusperpanjangan = new DefaultTableModel();



    
    public Main(String mail, String pass) {
        initComponents();
        //
        dashboard_pane();
        frontCondition();
        enable_false();
        
        //
        email = mail;
        password = pass;
        show_profile();
        show_buku();
        tanggalhari_ini();
        validasi_angka();
        show_datapeminjaman();
        show_history_datapeminjaman();
        show_statusPerpanjangan();
        show_datapeminjaman_diPerpanjangan();
        styleTable(tbl_buku);
        styleTable(tbl_datapinjam);
        styleTable(tbl_datapinjam1);
        styleTable(tbl_datapinjamhistory);
        styleTable(tbl_statusperpanjangan);
    }

    private Main() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Wrapper = new javax.swing.JPanel();
        leftPane = new javax.swing.JPanel();
        btnProfile = new javax.swing.JLabel();
        btnpeminjaman = new javax.swing.JLabel();
        btnPengembalian = new javax.swing.JLabel();
        btnPerpanjangan = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        imgLeft = new javax.swing.JLabel();
        rightPane = new javax.swing.JPanel();
        imgRight = new javax.swing.JLabel();
        profile_pane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_namalengkap = new javax.swing.JTextField();
        tf_email = new javax.swing.JTextField();
        tf_nim = new javax.swing.JTextField();
        tf_nohp = new javax.swing.JTextField();
        btn_batal = new javax.swing.JButton();
        tf_password = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        tf_konfirmpassword = new javax.swing.JPasswordField();
        btn_simpan = new javax.swing.JButton();
        peminjaman_pane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_buku = new javax.swing.JTable();
        tf_caribuku = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        tf_kodebuku = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_namabuku = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_jumlah = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_tenggat = new javax.swing.JTextField();
        btn_batalpinjam = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btn_pinjam = new javax.swing.JButton();
        pengembalian_pane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_datapinjamhistory = new javax.swing.JTable();
        btn_kembalikan = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btn_batalmengembalikan = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_datapinjam = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tf_transaksidipilih = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tf_idcetak = new javax.swing.JTextField();
        btn_cetak = new javax.swing.JButton();
        btn_batalcetak = new javax.swing.JButton();
        perpanjangan_pane = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_statusperpanjangan = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tf_transaksidipilih1 = new javax.swing.JTextField();
        btn_batalperpanjangan = new javax.swing.JButton();
        btn_perpanjang = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_datapinjam1 = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        dashboard_pane = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        Wrapper.setBackground(new java.awt.Color(255, 255, 255));
        Wrapper.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftPane.setBackground(new java.awt.Color(255, 255, 255));
        leftPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProfile.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(1, 193, 198));
        btnProfile.setText("I");
        btnProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProfileMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProfileMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProfileMouseEntered(evt);
            }
        });
        leftPane.add(btnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 243, 223, 40));

        btnpeminjaman.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        btnpeminjaman.setForeground(new java.awt.Color(1, 193, 198));
        btnpeminjaman.setText("I");
        btnpeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpeminjamanMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpeminjamanMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpeminjamanMouseEntered(evt);
            }
        });
        leftPane.add(btnpeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 308, 223, 40));

        btnPengembalian.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        btnPengembalian.setForeground(new java.awt.Color(1, 193, 198));
        btnPengembalian.setText("I");
        btnPengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPengembalianMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPengembalianMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPengembalianMouseEntered(evt);
            }
        });
        leftPane.add(btnPengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 370, 223, 40));

        btnPerpanjangan.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        btnPerpanjangan.setForeground(new java.awt.Color(1, 193, 198));
        btnPerpanjangan.setText("I");
        btnPerpanjangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerpanjanganMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPerpanjanganMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPerpanjanganMouseEntered(evt);
            }
        });
        leftPane.add(btnPerpanjangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 436, 223, 40));

        btnLogout.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(1, 193, 198));
        btnLogout.setText("I");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
        });
        leftPane.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 525, 223, 40));

        imgLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/kiri user.jpg"))); // NOI18N
        leftPane.add(imgLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 233, 600));

        Wrapper.add(leftPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 233, 600));

        rightPane.setBackground(new java.awt.Color(255, 255, 255));
        rightPane.setLayout(new java.awt.CardLayout());

        imgRight.setBackground(new java.awt.Color(255, 255, 255));
        imgRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/kanan user.jpg"))); // NOI18N
        rightPane.add(imgRight, "card2");

        profile_pane.setBackground(new java.awt.Color(255, 255, 255));
        profile_pane.setPreferredSize(new java.awt.Dimension(750, 600));
        profile_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Password");
        profile_pane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 120, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel5.setText("Profile__________");
        profile_pane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setText("Nama Lengkap");
        profile_pane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, -1));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel7.setText("Email");
        profile_pane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, -1));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel8.setText("NIM");
        profile_pane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, -1));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel9.setText("No HP");
        profile_pane.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 120, -1));
        profile_pane.add(tf_namalengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 540, 40));
        profile_pane.add(tf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 540, 40));
        profile_pane.add(tf_nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 540, 40));
        profile_pane.add(tf_nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 540, 40));

        btn_batal.setBackground(new java.awt.Color(255, 255, 255));
        btn_batal.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        profile_pane.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 120, 40));
        profile_pane.add(tf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 540, 40));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel10.setText("Konfirmasi Password");
        profile_pane.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 160, -1));
        profile_pane.add(tf_konfirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 540, 40));

        btn_simpan.setBackground(new java.awt.Color(255, 255, 255));
        btn_simpan.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btn_simpan.setText("Update");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        profile_pane.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 120, 40));

        rightPane.add(profile_pane, "card3");

        peminjaman_pane.setBackground(new java.awt.Color(255, 255, 255));
        peminjaman_pane.setPreferredSize(new java.awt.Dimension(750, 600));
        peminjaman_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel2.setText("Peminjaman__________");
        peminjaman_pane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        tbl_buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_buku.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tbl_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_buku);

        peminjaman_pane.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 330, 370));

        tf_caribuku.setFont(new java.awt.Font("Helvetica", 2, 13)); // NOI18N
        tf_caribuku.setForeground(new java.awt.Color(102, 102, 102));
        tf_caribuku.setText("cari berdasarkan nama buku");
        tf_caribuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_caribukuMouseClicked(evt);
            }
        });
        peminjaman_pane.add(tf_caribuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 250, 30));

        btn_cari.setBackground(new java.awt.Color(255, 255, 255));
        btn_cari.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        btn_cari.setText("cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        peminjaman_pane.add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 80, 30));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 2, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("*klik tabel untuk memilih buku!");
        peminjaman_pane.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 150, -1));

        tf_kodebuku.setEditable(false);
        peminjaman_pane.add(tf_kodebuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 280, 40));

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel12.setText("Buku");
        peminjaman_pane.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 50, -1));

        tf_namabuku.setEditable(false);
        peminjaman_pane.add(tf_namabuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 280, 40));

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel13.setText("Jumlah");
        peminjaman_pane.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 50, -1));
        peminjaman_pane.add(tf_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 280, 40));

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel14.setText("Tenggat");
        peminjaman_pane.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 80, -1));

        tf_tenggat.setEditable(false);
        peminjaman_pane.add(tf_tenggat, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 280, 40));

        btn_batalpinjam.setBackground(new java.awt.Color(255, 255, 255));
        btn_batalpinjam.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        btn_batalpinjam.setText("Batal");
        btn_batalpinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalpinjamActionPerformed(evt);
            }
        });
        peminjaman_pane.add(btn_batalpinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 100, 40));

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel15.setText("Kode");
        peminjaman_pane.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 50, -1));

        btn_pinjam.setBackground(new java.awt.Color(255, 255, 255));
        btn_pinjam.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        btn_pinjam.setText("Pinjam");
        btn_pinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pinjamActionPerformed(evt);
            }
        });
        peminjaman_pane.add(btn_pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 100, 40));

        rightPane.add(peminjaman_pane, "card4");

        pengembalian_pane.setBackground(new java.awt.Color(255, 255, 255));
        pengembalian_pane.setPreferredSize(new java.awt.Dimension(750, 600));
        pengembalian_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel3.setText("History__________");
        pengembalian_pane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        tbl_datapinjamhistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_datapinjamhistory.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tbl_datapinjamhistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_datapinjamhistoryMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_datapinjamhistory);

        pengembalian_pane.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 710, 190));

        btn_kembalikan.setBackground(new java.awt.Color(255, 255, 255));
        btn_kembalikan.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        btn_kembalikan.setText("Kembalikan");
        btn_kembalikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembalikanActionPerformed(evt);
            }
        });
        pengembalian_pane.add(btn_kembalikan, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 120, 40));

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 2, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 51));
        jLabel16.setText("*klik tabel untuk memilih data!");
        pengembalian_pane.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, 20));

        btn_batalmengembalikan.setBackground(new java.awt.Color(255, 255, 255));
        btn_batalmengembalikan.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        btn_batalmengembalikan.setText("Batal");
        btn_batalmengembalikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalmengembalikanActionPerformed(evt);
            }
        });
        pengembalian_pane.add(btn_batalmengembalikan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 100, 40));

        tbl_datapinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_datapinjam.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tbl_datapinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_datapinjamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_datapinjam);

        pengembalian_pane.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 710, 140));

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel17.setText("Pengembalian__________");
        pengembalian_pane.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel19.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel19.setText("ID Transaksi");
        pengembalian_pane.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 120, -1));

        tf_transaksidipilih.setEditable(false);
        tf_transaksidipilih.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        tf_transaksidipilih.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pengembalian_pane.add(tf_transaksidipilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 40, 40));

        jLabel22.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel22.setText("ID Transaksi");
        pengembalian_pane.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 120, -1));

        tf_idcetak.setEditable(false);
        tf_idcetak.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        tf_idcetak.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pengembalian_pane.add(tf_idcetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 40, 40));

        btn_cetak.setBackground(new java.awt.Color(255, 255, 255));
        btn_cetak.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        btn_cetak.setText("Cetak");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });
        pengembalian_pane.add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 100, 40));

        btn_batalcetak.setBackground(new java.awt.Color(255, 255, 255));
        btn_batalcetak.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        btn_batalcetak.setText("Batal");
        btn_batalcetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalcetakActionPerformed(evt);
            }
        });
        pengembalian_pane.add(btn_batalcetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 100, 40));

        rightPane.add(pengembalian_pane, "card5");

        perpanjangan_pane.setBackground(new java.awt.Color(255, 255, 255));
        perpanjangan_pane.setPreferredSize(new java.awt.Dimension(750, 600));
        perpanjangan_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel4.setText("Status__________");
        perpanjangan_pane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        tbl_statusperpanjangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_statusperpanjangan.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tbl_statusperpanjangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_statusperpanjanganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl_statusperpanjanganMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_statusperpanjangan);

        perpanjangan_pane.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 710, 160));

        jLabel20.setFont(new java.awt.Font("Helvetica Neue", 2, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 51, 51));
        jLabel20.setText("*klik tabel untuk memilih data!");
        perpanjangan_pane.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, 20));

        jLabel21.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel21.setText("ID Transaksi");
        perpanjangan_pane.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 120, -1));

        tf_transaksidipilih1.setEditable(false);
        tf_transaksidipilih1.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        tf_transaksidipilih1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        perpanjangan_pane.add(tf_transaksidipilih1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 40, 40));

        btn_batalperpanjangan.setBackground(new java.awt.Color(255, 255, 255));
        btn_batalperpanjangan.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        btn_batalperpanjangan.setText("Batal");
        btn_batalperpanjangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalperpanjanganActionPerformed(evt);
            }
        });
        perpanjangan_pane.add(btn_batalperpanjangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 100, 40));

        btn_perpanjang.setBackground(new java.awt.Color(255, 255, 255));
        btn_perpanjang.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        btn_perpanjang.setText("Perpanjang");
        btn_perpanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_perpanjangActionPerformed(evt);
            }
        });
        perpanjangan_pane.add(btn_perpanjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 120, 40));

        tbl_datapinjam1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_datapinjam1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tbl_datapinjam1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_datapinjam1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbl_datapinjam1);

        perpanjangan_pane.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 710, 140));

        jLabel23.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel23.setText("Perpanjangan__________");
        perpanjangan_pane.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        rightPane.add(perpanjangan_pane, "card6");

        dashboard_pane.setBackground(new java.awt.Color(255, 255, 255));
        dashboard_pane.setPreferredSize(new java.awt.Dimension(750, 600));
        dashboard_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Selamat Datang");
        dashboard_pane.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 730, -1));

        rightPane.add(dashboard_pane, "card6");

        Wrapper.add(rightPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 760, 600));

        getContentPane().add(Wrapper, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    void styleTable(JTable tblTest){
        tblTest.setShowHorizontalLines(true);
        tblTest.setGridColor(new Color(230,230,230));
        tblTest.setBackground(Color.WHITE);
        tblTest.setRowHeight(40);
        tblTest.setOpaque(false);
        tblTest.getTableHeader().setReorderingAllowed(false);
        tblTest.getTableHeader().setBackground(Color.white);
        tblTest.getTableHeader().setDefaultRenderer(new HeaderColor());
    }
    public class HeaderColor extends DefaultTableCellRenderer {

        public HeaderColor() {
            setOpaque(true);
        }

        public Component getTableCellRendererComponent(JTable table, Object value, boolean selected, boolean focused, int row, int column) {
            super.getTableCellRendererComponent(table, value, selected, focused, row, column);

            setBackground(new java.awt.Color(255,255,255));
            setBorder(noFocusBorder);
            return this;
        }

    }
    
    void show_history_datapeminjaman(){
        Object[] kolom = {
            "ID","Buku", "Qty", "Tgl Pinjam", "Tgl Tenggat", "Tgl Kembali", "Denda", "Status"
        };
        modelhistory = new DefaultTableModel(null, kolom);
        tbl_datapinjamhistory.setModel(modelhistory);
        try {
          st = conn.createStatement();
          rs = st.executeQuery("SELECT "
                  + "transaksi.id_trans, buku.namabuku, transaksi.qty, transaksi.tgl_pinjam, transaksi.tgl_tenggat, transaksi.tgl_kembali, transaksi.denda, transaksi.status "
                  + "FROM `transaksi`, `buku`, `user` "
                  + "WHERE user.id_user = transaksi.id_user "
                  + "AND buku.id_buku = transaksi.id_buku "
                  + "AND transaksi.id_user = '"+id_user+"'");
          while (rs.next()) {
            Object[] data = {
              rs.getString("id_trans"),
              rs.getString("namabuku"),
              rs.getString("qty"),
              rs.getString("tgl_pinjam"),
              rs.getString("tgl_tenggat"),
              rs.getString("tgl_kembali"),
              rs.getString("denda"),
              rs.getString("status")
            };
              modelhistory.addRow(data);
          }
        } catch(SQLException e) {
            System.out.println("1"+e.getMessage());
        }
    }
    void show_datapeminjaman(){
        Object[] kolom = {
            "ID", "Buku", "Qty", "Tgl Pinjam", "Tgl Tenggat"
        };
        modelpinjam = new DefaultTableModel(null, kolom);
        tbl_datapinjam.setModel(modelpinjam);
        try {
          st = conn.createStatement();
          rs = st.executeQuery("SELECT "
                  + "transaksi.id_trans, buku.namabuku, transaksi.qty, transaksi.tgl_pinjam, transaksi.tgl_tenggat "
                  + "FROM transaksi "
                  + "JOIN buku ON buku.id_buku = transaksi.id_buku "
                  + "JOIN user ON user.id_user = transaksi.id_user "
                  + "WHERE transaksi.tgl_kembali IS NULL "
                  + "AND transaksi.id_user = "+id_user);
          while (rs.next()) {
            Object[] data = {
              rs.getString("id_trans"),
              rs.getString("namabuku"),
              rs.getString("qty"),
              rs.getString("tgl_pinjam"),
              rs.getString("tgl_tenggat")
            };
              modelpinjam.addRow(data);
          }
        } catch(SQLException e) {
            System.out.println("2"+e.getMessage());
        }
    }
    void show_datapeminjaman_diPerpanjangan(){
        Object[] kolom = {
            "ID", "Buku", "Qty", "Tgl Pinjam", "Tgl Tenggat"
        };
        modelpinjamdiperpanjangan = new DefaultTableModel(null, kolom);
        tbl_datapinjam1.setModel(modelpinjamdiperpanjangan);
        try {
          st = conn.createStatement();
//          rs = st.executeQuery("SELECT "
//                  + "transaksi.id_trans, user.username, buku.namabuku, transaksi.qty, transaksi.tgl_pinjam, transaksi.tgl_tenggat, transaksi.tgl_kembali, transaksi.denda "
//                  + "FROM `transaksi`, `buku`, `user`, `perpanjangan` "
//                  + "WHERE user.id_user = transaksi.id_user "
//                  + "AND buku.id_buku = transaksi.id_buku "
//                  + "AND transaksi.id_trans = perpanjangan.id_perpanjangan "
//                  + "AND transaksi.id_user = '"+id_user+"' AND transaksi.tgl_kembali IS NULL "
//                  + "AND perpanjangan.status = 'diproses'");
            rs = st.executeQuery("SELECT "
                  + "transaksi.id_trans, buku.namabuku, transaksi.qty, transaksi.tgl_pinjam, transaksi.tgl_tenggat "
                  + "FROM transaksi "
                  + "JOIN buku ON buku.id_buku = transaksi.id_buku "
                  + "JOIN user ON user.id_user = transaksi.id_user "
                  + "WHERE transaksi.tgl_kembali IS NULL "
                  + "AND transaksi.id_user = "+id_user);
          while (rs.next()) {
            Object[] data = {
              rs.getString("id_trans"),
//              rs.getString("username"),
              rs.getString("namabuku"),
              rs.getString("qty"),
              rs.getString("tgl_pinjam"),
              rs.getString("tgl_tenggat")
            };
              modelpinjamdiperpanjangan.addRow(data);
          }
        } catch(SQLException e) {
            System.out.println("3"+e.getMessage());
        }
    }
    
    void show_statusPerpanjangan(){
        Object[] kolom = {
            "ID", "Buku", "Qty", "Tgl Pinjam", "Tgl Tenggat", "Tgl Diajukan", "Status"
        };
        modelstatusperpanjangan = new DefaultTableModel(null, kolom);
        tbl_statusperpanjangan.setModel(modelstatusperpanjangan);
        try {
          st = conn.createStatement();
          rs = st.executeQuery("SELECT "
                  + "transaksi.id_trans, buku.namabuku, transaksi.qty, transaksi.tgl_pinjam, transaksi.tgl_tenggat, perpanjangan.tgl_perpanjangan as tgl_diajukan, perpanjangan.status "
                  + "FROM `transaksi`, `buku`, `user`, `perpanjangan` "
                  + "WHERE user.id_user = transaksi.id_user  "
                  + "AND buku.id_buku = transaksi.id_buku  "
                  + "AND transaksi.id_trans = perpanjangan.id_trans "
                  + "AND transaksi.id_user = "+id_user);
          while (rs.next()) {
            Object[] data = {
              rs.getString("id_trans"),
              rs.getString("namabuku"),
              rs.getString("qty"),
              rs.getString("tgl_pinjam"),
              rs.getString("tgl_tenggat"),
              rs.getString("tgl_diajukan"),
              rs.getString("status"),
            };
              modelstatusperpanjangan.addRow(data);
          }
        } catch(SQLException e) {
            System.out.println("4"+e.getMessage());
        }
    }
    
    void tanggalhari_ini(){
        // Get today's date
        LocalDate currentDate = LocalDate.now();
        // Format the date using DateTimeFormatter
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String formattedTodayDate = currentDate.format(formatter);
        tglhari_ini = formattedTodayDate;
    }
    
    void show_buku(){
        Object[] kolom = {
            "ID", "Buku", "Stok", "Penulis", "Penerbit"
        };
        model = new DefaultTableModel(null, kolom);
        tbl_buku.setModel(model);
        try {
          st = conn.createStatement();
          rs = st.executeQuery("SELECT * FROM buku");
          while (rs.next()) {
            Object[] data = {
              rs.getString("id_buku"),
              rs.getString("namabuku"),
              rs.getString("stok"),
              rs.getString("penulis"),
              rs.getString("penerbit")
            };
              model.addRow(data);
          }
        } catch(SQLException e) {
            System.out.println("5"+e.getMessage());
        }
    }
    void show_profile(){
        try {
            String query = "SELECT * FROM user WHERE email=? AND password=?";
            ps = conn.prepareStatement(query);
            ps.setString(1, email);
            ps.setString(2, password);
            rs = ps.executeQuery();
            if (rs.next()) {
                id_user = rs.getString("id_user");
                username = rs.getString("username");
                nim = rs.getString("nim");
                nohp = rs.getString("nohp");
                role = rs.getString("role");
            }
            tf_namalengkap.setText(username);
            tf_nim.setText(nim);
            tf_email.setText(email);
            tf_nohp.setText(nohp);
            tf_password.setText(password);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "gagal menampilkan data profile " + e.getMessage());
        }
    }
    
    void enable_false(){
        tf_email.setEnabled(false);
        tf_namalengkap.setEnabled(false);
        tf_nim.setEnabled(false);
        tf_nohp.setEnabled(false);
        tf_password.setEnabled(false);
        tf_konfirmpassword.setEnabled(false);
        btn_simpan.setText("Update");
        btn_batal.setEnabled(false);
        btn_pinjam.setEnabled(false);
        btn_kembalikan.setEnabled(false);
        btn_perpanjang.setEnabled(false);
        btn_cetak.setEnabled(false);
    }
    void enable_true(){
        tf_email.setEnabled(true);
        tf_namalengkap.setEnabled(true);
        tf_nim.setEnabled(true);
        tf_nohp.setEnabled(true);
        tf_password.setEnabled(true);
        tf_konfirmpassword.setEnabled(true);
        btn_simpan.setText("Simpan");
        btn_batal.setEnabled(true);
    }
    void clear_profile(){
        tf_email.setText("");
        tf_namalengkap.setText("");
        tf_nim.setText("");
        tf_nohp.setText("");
        tf_password.setText("");
        tf_konfirmpassword.setText("");
    }
    void clear_pinjam(){
        tf_namabuku.setText("");
        tf_kodebuku.setText("");
        tf_jumlah.setText("");
        tf_tenggat.setText("");
        btn_pinjam.setEnabled(false);
    }
    void dashboard_pane(){
        rightPane.removeAll();
        rightPane.repaint();
        rightPane.revalidate();
        rightPane.add(dashboard_pane);
        rightPane.repaint();
        rightPane.revalidate();
    }
    private void btnProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMouseClicked
        // TODO add your handling code here:
        rightPane.removeAll();
        rightPane.repaint();
        rightPane.revalidate();
        //
        rightPane.add(profile_pane);
        rightPane.repaint();
        rightPane.revalidate();
//        JOptionPane.showMessageDialog(this, id_user + username + email + password + nim );
    }//GEN-LAST:event_btnProfileMouseClicked

    private void btnProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMouseExited
        // TODO add your handling code here:
        btnProfile.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnProfileMouseExited

    private void btnProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMouseEntered
        // TODO add your handling code here:
        btnProfile.setForeground(new Color(1,193,198));
    }//GEN-LAST:event_btnProfileMouseEntered

    private void btnpeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpeminjamanMouseClicked
        // TODO add your handling code here:
        rightPane.removeAll();
        rightPane.repaint();
        rightPane.revalidate();
        //
        rightPane.add(peminjaman_pane);
        rightPane.repaint();
        rightPane.revalidate();
    }//GEN-LAST:event_btnpeminjamanMouseClicked

    private void btnpeminjamanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpeminjamanMouseExited
        // TODO add your handling code here:
        btnpeminjaman.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnpeminjamanMouseExited

    private void btnpeminjamanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpeminjamanMouseEntered
        // TODO add your handling code here:
        btnpeminjaman.setForeground(new Color(1,193,198));
    }//GEN-LAST:event_btnpeminjamanMouseEntered

    private void btnPengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPengembalianMouseClicked
        // TODO add your handling code here:
        rightPane.removeAll();
        rightPane.repaint();
        rightPane.revalidate();
        //
        rightPane.add(pengembalian_pane);
        rightPane.repaint();
        rightPane.revalidate();
    }//GEN-LAST:event_btnPengembalianMouseClicked

    private void btnPengembalianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPengembalianMouseExited
        // TODO add your handling code here:
        btnPengembalian.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnPengembalianMouseExited

    private void btnPengembalianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPengembalianMouseEntered
        // TODO add your handling code here:
        btnPengembalian.setForeground(new Color(1,193,198));
    }//GEN-LAST:event_btnPengembalianMouseEntered

    private void btnPerpanjanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerpanjanganMouseClicked
        // TODO add your handling code here:
        rightPane.removeAll();
        rightPane.repaint();
        rightPane.revalidate();
        //
        rightPane.add(perpanjangan_pane);
        rightPane.repaint();
        rightPane.revalidate();
    }//GEN-LAST:event_btnPerpanjanganMouseClicked

    private void btnPerpanjanganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerpanjanganMouseExited
        // TODO add your handling code here:
        btnPerpanjangan.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnPerpanjanganMouseExited

    private void btnPerpanjanganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerpanjanganMouseEntered
        // TODO add your handling code here:
        btnPerpanjangan.setForeground(new Color(1,193,198));
    }//GEN-LAST:event_btnPerpanjanganMouseEntered

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        int opsi = JOptionPane.showConfirmDialog(null, "Apakah anda ingin Keluar ?");
        switch(opsi){
            case JOptionPane.YES_OPTION:
            new FrontView().setVisible(true);
            this.dispose();
            break;
            case JOptionPane.NO_OPTION:
            break;
            default:
            break;
        }
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        btnLogout.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        btnLogout.setForeground(new Color(1,193,198));
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        enable_false();

    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:     
        if (btn_simpan.getText().equals("Simpan")) {
            if (tf_namalengkap.getText().equals("") 
                || tf_nim.getText().equals("") 
                || tf_email.getText().equals("") 
                || tf_nohp.getText().equals("") 
                || tf_password.getText().equals("")
                || tf_konfirmpassword.getText().equals("")
                || !isValidEmail(tf_email.getText())) {
                JOptionPane.showMessageDialog(this, "Form masih kosong atau data tidak valid");
            }else{ 
                if (tf_password.getText().equals(tf_konfirmpassword.getText())) {
                    try {
                        String query = "UPDATE user SET "
                            + "username=?,nim=?,email=?,nohp=?,password=?,role=? "
                            + "WHERE id_user=?";
                        ps = conn.prepareStatement(query);
                        ps.setString(1, tf_namalengkap.getText());
                        ps.setString(2, tf_nim.getText());
                        ps.setString(3, tf_email.getText());
                        ps.setString(4, tf_nohp.getText());
                        ps.setString(5, tf_password.getText());
                        ps.setString(6, "2");
                        ps.setString(7, id_user);
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(this, "berhasil menyimpan data");
                        enable_false();
                    }catch(SQLException e){
                        JOptionPane.showMessageDialog(this, "Eror "+e.getMessage());
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Password tidak sama!");
                }
            }
        }else{
            enable_true();
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void tbl_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bukuMouseClicked
        // TODO add your handling code here:
        btn_pinjam.setEnabled(true);
        int selectedRow = tbl_buku.getSelectedRow();
        if (selectedRow != -1) {
            id_buku = tbl_buku.getValueAt(selectedRow, 0).toString();
            tf_kodebuku.setText(tbl_buku.getValueAt(selectedRow, 0).toString());
            tf_namabuku.setText(tbl_buku.getValueAt(selectedRow, 1).toString());
            //
            LocalDate currentDate = LocalDate.now();
            LocalDate futureDate = currentDate.plusDays(10);
            // Format the date using DateTimeFormatter
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            String formattedFutureDate = futureDate.format(formatter);
            tf_tenggat.setText(formattedFutureDate);
        }
    }//GEN-LAST:event_tbl_bukuMouseClicked

    private void btn_batalpinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalpinjamActionPerformed
        // TODO add your handling code here:
        clear_pinjam();
    }//GEN-LAST:event_btn_batalpinjamActionPerformed

    private boolean isNumeric(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    private void btn_pinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pinjamActionPerformed
        // TODO add your handling code here:
        if (tf_jumlah.getText().equals("") || !isNumeric(tf_jumlah.getText())) {
            JOptionPane.showMessageDialog(this, "masukan jumlah buku terlebih dahulu! atau inputan tidak valid");
        }else{
            try {
                String stokQuery = "SELECT stok FROM buku WHERE id_buku=?";
                PreparedStatement stokPs = conn.prepareStatement(stokQuery);
                stokPs.setString(1, tf_kodebuku.getText());
                ResultSet stokRs = stokPs.executeQuery();
                if (stokRs.next()) {
                    int stokBuku = stokRs.getInt("stok");
                    int jumlahPeminjaman = Integer.parseInt(tf_jumlah.getText());
                    if (stokBuku >= jumlahPeminjaman) {
                        String query = "INSERT INTO transaksi"
                            + "(id_user,id_buku,qty,tgl_pinjam,tgl_tenggat) "
                            + "VALUES (?, ? ,?, ?, ?)";
                        ps = conn.prepareStatement(query);
                        ps.setString(1, id_user);
                        ps.setString(2, tf_kodebuku.getText());
                        ps.setString(3, tf_jumlah.getText());
                        ps.setString(4, tglhari_ini);
                        ps.setString(5, tf_tenggat.getText());
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(this, "berhasil meminjam buku");
                        show_datapeminjaman();
                        show_history_datapeminjaman();
                        show_buku();
                        clear_pinjam();
                    }else{
                        JOptionPane.showMessageDialog(this, "Stok buku tidak cukup untuk peminjaman.");
                    }
                }
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, "Eror "+e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_pinjamActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        String keyword = tf_caribuku.getText();
        Object[] kolom = {
            "ID", "Buku", "Stok", "Penulis", "Penerbit"
        };
        model = new DefaultTableModel(null, kolom);
        tbl_buku.setModel(model);
        try {
          st = conn.createStatement();
          rs = st.executeQuery("SELECT * FROM buku WHERE namabuku LIKE '%"+keyword+"%'");
          while (rs.next()) {
            Object[] data = {
              rs.getString("id_buku"),
              rs.getString("namabuku"),
              rs.getString("stok"),
              rs.getString("penulis"),
              rs.getString("penerbit")
            };
              model.addRow(data);
          }
        } catch(SQLException e) {
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_btn_cariActionPerformed

    void dendaPinjam(){
        denda = 0;
        selisihTenggat = 0;
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date dateTenggat = sdf.parse(tgl_tenggat);
            Date dateKembali = sdf.parse(tglhari_ini);

            long selisihMillis = dateKembali.getTime() - dateTenggat.getTime();
            long selisihHari = TimeUnit.DAYS.convert(selisihMillis, TimeUnit.MILLISECONDS);

            selisihHari = (selisihHari < 0) ? 0 : selisihHari;
            denda = selisihHari * 1000;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void btn_kembalikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembalikanActionPerformed
        // TODO add your handling code here:
        dendaPinjam();
        String status = "";
        if (denda > 0) {
            status = "belum lunas";
        }else{
            status = "lunas";
        }
        try {
            String query = "UPDATE transaksi SET "
                + "tgl_kembali=?,denda=?, status=? WHERE id_trans=?";
            ps = conn.prepareStatement(query);
            ps.setString(1, tglhari_ini);
            ps.setString(2, String.valueOf(denda));
            ps.setString(3, status);
            ps.setString(4, id_trans);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "berhasil mengembalikan buku");
            if (denda != 0) {
                JOptionPane.showMessageDialog(this, "Anda dikenakan denda sebesar Rp."+denda +"\nHubungi admin untuk melunasi denda");
            }
            show_datapeminjaman();
            show_history_datapeminjaman();
            //clear
            tf_transaksidipilih.setText("");
            tgl_tenggat = "00-00-0000";
            denda = 0;
            id_trans = "0";
            btn_kembalikan.setEnabled(false);
            enable_false();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Eror "+e.getMessage());
        }
    }//GEN-LAST:event_btn_kembalikanActionPerformed

    private void btn_batalmengembalikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalmengembalikanActionPerformed
        // TODO add your handling code here:
        btn_kembalikan.setEnabled(false);
        tf_transaksidipilih.setText("");
        tgl_tenggat = "00-00-0000";
        id_trans = "0";
    }//GEN-LAST:event_btn_batalmengembalikanActionPerformed

    private void tf_caribukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_caribukuMouseClicked
        // TODO add your handling code here:
        tf_caribuku.setText("");
    }//GEN-LAST:event_tf_caribukuMouseClicked

    private void btn_batalperpanjanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalperpanjanganActionPerformed
        // TODO add your handling code here:
        btn_perpanjang.setEnabled(false);
        tf_transaksidipilih1.setText("");
        tgl_tenggat = "00-00-0000";
        id_trans = "0";
    }//GEN-LAST:event_btn_batalperpanjanganActionPerformed

    private void btn_perpanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_perpanjangActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        //
        try {
            String checkNIMQuery = "SELECT * FROM transaksi WHERE id_trans=?";
            ps = conn.prepareStatement(checkNIMQuery);
            ps.setString(1, id_trans);
            ResultSet rst = ps.executeQuery();
            if (rst.next()) {
                tgl_tenggat_lama = rst.getString("tgl_tenggat");
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        try {
            Date dateTenggat = sdf.parse(tgl_tenggat);
            Date dateKembali = sdf.parse(tglhari_ini);
            long selisihMillis = dateKembali.getTime() - dateTenggat.getTime();
            long selisihHari = TimeUnit.DAYS.convert(selisihMillis, TimeUnit.MILLISECONDS);
            if (selisihHari >= -2 && selisihHari <= 0) {
                try {
                    String query = "INSERT INTO perpanjangan(id_trans,tgl_perpanjangan,tgl_tenggat_lama) "
                            + "VALUES(?,?,?)";
                    ps = conn.prepareStatement(query);
                    ps.setString(1, id_trans);
                    ps.setString(2, tglhari_ini);
                    ps.setString(3, tgl_tenggat_lama);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Berhasil mengajukan penpanjangan");
                    show_datapeminjaman();
                    show_history_datapeminjaman();
                    show_statusPerpanjangan();
                    show_datapeminjaman_diPerpanjangan();
                    //clear
                    tf_transaksidipilih1.setText("");
                    tgl_tenggat = "00-00-0000";
                    id_trans = "0";
                    tgl_tenggat_lama = "00-00-0000";
                    btn_perpanjang.setEnabled(false);
                    enable_false();
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(this, "Eror "+e.getMessage());
                }
            }else if(selisihHari > 0){
                JOptionPane.showMessageDialog(this, "Tidak dapat melakukan perpanjangan\nKarena Sudah melebihi Tanggal tenggat");
            }else{
                JOptionPane.showMessageDialog(this, "Tidak dapat melakukan Perpanjangan \nSebelum H-2 Tenggat");
            }
            
        } catch (HeadlessException | ParseException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_perpanjangActionPerformed

    private void tbl_datapinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_datapinjamMouseClicked
        // TODO add your handling code here:
        btn_kembalikan.setEnabled(true);
        btn_batal.setEnabled(true);
        int selectedRow = tbl_datapinjam.getSelectedRow();
        if (selectedRow != -1) {
            id_trans = tbl_datapinjam.getValueAt(selectedRow, 0).toString();
            tgl_tenggat = tbl_datapinjam.getValueAt(selectedRow, 4).toString();
            tf_transaksidipilih.setText(id_trans);
        }
//        JOptionPane.showMessageDialog(this, tgl_tenggat);
        
    }//GEN-LAST:event_tbl_datapinjamMouseClicked

    private void tbl_statusperpanjanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_statusperpanjanganMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tbl_statusperpanjanganMouseClicked

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        // TODO add your handling code here:
        try {
            String path = "/Users/macbookpro/NetBeansProjects/ProjectAkhir/src/Report/nota_peminjaman.jrxml";
            HashMap hash = new HashMap();
            hash.put("kode", tf_idcetak.getText());
            JasperReport jrpt = JasperCompileManager.compileReport(path);
            JasperPrint jprint = JasperFillManager.fillReport(jrpt, hash, conn);
            JasperViewer.viewReport(jprint, false);
        } catch (JRException e) {
            System.out.println("error : " + e.getMessage());
        }
    }//GEN-LAST:event_btn_cetakActionPerformed

    private void tbl_datapinjamhistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_datapinjamhistoryMouseClicked
        // TODO add your handling code here:
        btn_cetak.setEnabled(true);
        int selectedRow = tbl_datapinjamhistory.getSelectedRow();
        if (selectedRow != -1) {
            String id = tbl_datapinjamhistory.getValueAt(selectedRow, 0).toString();
            tf_idcetak.setText(id);
        }
    }//GEN-LAST:event_tbl_datapinjamhistoryMouseClicked

    private void btn_batalcetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalcetakActionPerformed
        // TODO add your handling code here:
        btn_cetak.setEnabled(false);
        tf_idcetak.setText("");
    }//GEN-LAST:event_btn_batalcetakActionPerformed

    private void tbl_datapinjam1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_datapinjam1MouseClicked
        // TODO add your handling code here:
        btn_perpanjang.setEnabled(true);
        int selectedRow = tbl_datapinjam1.getSelectedRow();
        if (selectedRow != -1) {
            id_trans = tbl_datapinjam1.getValueAt(selectedRow, 0).toString();
            tgl_tenggat = tbl_datapinjam1.getValueAt(selectedRow, 4).toString();
            tf_transaksidipilih1.setText(id_trans);
        }
    }//GEN-LAST:event_tbl_datapinjam1MouseClicked

    private void tbl_statusperpanjanganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_statusperpanjanganMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_statusperpanjanganMouseEntered
    public void frontCondition(){
        btnLogout.setForeground(Color.WHITE);
        btnPerpanjangan.setForeground(Color.WHITE);
        btnProfile.setForeground(Color.WHITE);
        btnpeminjaman.setForeground(Color.WHITE);
        btnPengembalian.setForeground(Color.WHITE);
    }
    void validasi_angka(){
        tf_nim.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char inputChar = e.getKeyChar();
                if (!Character.isDigit(inputChar)) {
                    e.consume();
                }
            }
        });
        tf_nohp.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char inputChar = e.getKeyChar();
                if (!Character.isDigit(inputChar)) {
                    e.consume();
                }
            }
        });
        tf_jumlah.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char inputChar = e.getKeyChar();
                if (!Character.isDigit(inputChar)) {
                    e.consume();
                }
            }
        });
    }
    private boolean isValidEmail(String email) {
        // Format email Gmail menggunakan regular expression
        String regex = "^[a-zA-Z0-9_]+@gmail\\.com$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Wrapper;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnPengembalian;
    private javax.swing.JLabel btnPerpanjangan;
    private javax.swing.JLabel btnProfile;
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_batalcetak;
    private javax.swing.JButton btn_batalmengembalikan;
    private javax.swing.JButton btn_batalperpanjangan;
    private javax.swing.JButton btn_batalpinjam;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_kembalikan;
    private javax.swing.JButton btn_perpanjang;
    private javax.swing.JButton btn_pinjam;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JLabel btnpeminjaman;
    private javax.swing.JPanel dashboard_pane;
    private javax.swing.JLabel imgLeft;
    private javax.swing.JLabel imgRight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel leftPane;
    private javax.swing.JPanel peminjaman_pane;
    private javax.swing.JPanel pengembalian_pane;
    private javax.swing.JPanel perpanjangan_pane;
    private javax.swing.JPanel profile_pane;
    private javax.swing.JPanel rightPane;
    private javax.swing.JTable tbl_buku;
    private javax.swing.JTable tbl_datapinjam;
    private javax.swing.JTable tbl_datapinjam1;
    private javax.swing.JTable tbl_datapinjamhistory;
    private javax.swing.JTable tbl_statusperpanjangan;
    private javax.swing.JTextField tf_caribuku;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_idcetak;
    private javax.swing.JTextField tf_jumlah;
    private javax.swing.JTextField tf_kodebuku;
    private javax.swing.JPasswordField tf_konfirmpassword;
    private javax.swing.JTextField tf_namabuku;
    private javax.swing.JTextField tf_namalengkap;
    private javax.swing.JTextField tf_nim;
    private javax.swing.JTextField tf_nohp;
    private javax.swing.JPasswordField tf_password;
    private javax.swing.JTextField tf_tenggat;
    private javax.swing.JTextField tf_transaksidipilih;
    private javax.swing.JTextField tf_transaksidipilih1;
    // End of variables declaration//GEN-END:variables
}
