/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectakhir;
import controller.koneksi;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author macbookpro
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    
    private ResultSet rs;
    private Statement st;
    private PreparedStatement ps;
    Connection conn = koneksi.Koneksi();
    
    public Signup() {
        initComponents();
        
        tf_nama.setBackground(new Color(0,0,0,0));
        tf_nohp.setBackground(new Color(0,0,0,0));
        tf_password.setBackground(new Color(0,0,0,0));
        cb_tampil.setBackground(new Color(0,0,0,0));
        tf_email.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signup_pane = new javax.swing.JPanel();
        tf_nama = new javax.swing.JTextField();
        tf_nohp = new javax.swing.JTextField();
        tf_email = new javax.swing.JTextField();
        tf_password = new javax.swing.JPasswordField();
        tf_nim = new javax.swing.JTextField();
        cb_tampil = new javax.swing.JCheckBox();
        btn_back = new javax.swing.JLabel();
        button_signin = new javax.swing.JPanel();
        btn_signup = new javax.swing.JLabel();
        gambarSignup = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        signup_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_nama.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tf_nama.setForeground(new java.awt.Color(153, 153, 153));
        tf_nama.setBorder(null);
        signup_pane.add(tf_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 231, 220, 33));

        tf_nohp.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tf_nohp.setForeground(new java.awt.Color(153, 153, 153));
        tf_nohp.setBorder(null);
        signup_pane.add(tf_nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 220, 33));

        tf_email.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tf_email.setForeground(new java.awt.Color(153, 153, 153));
        tf_email.setBorder(null);
        signup_pane.add(tf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 413, 220, 40));

        tf_password.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tf_password.setForeground(new java.awt.Color(153, 153, 153));
        tf_password.setBorder(null);
        signup_pane.add(tf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 220, 40));

        tf_nim.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tf_nim.setForeground(new java.awt.Color(153, 153, 153));
        tf_nim.setBorder(null);
        signup_pane.add(tf_nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 220, 33));

        cb_tampil.setBackground(new java.awt.Color(255, 255, 255));
        cb_tampil.setForeground(new java.awt.Color(102, 204, 255));
        cb_tampil.setBorder(null);
        cb_tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tampilActionPerformed(evt);
            }
        });
        signup_pane.add(cb_tampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 473, -1, 40));

        btn_back.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("<");
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        signup_pane.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        button_signin.setBackground(new java.awt.Color(255, 255, 255));
        button_signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_signinMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_signinMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_signinMouseEntered(evt);
            }
        });

        btn_signup.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btn_signup.setForeground(new java.awt.Color(1, 193, 198));
        btn_signup.setText("Register");
        btn_signup.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout button_signinLayout = new javax.swing.GroupLayout(button_signin);
        button_signin.setLayout(button_signinLayout);
        button_signinLayout.setHorizontalGroup(
            button_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_signinLayout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(btn_signup)
                .addGap(131, 131, 131))
        );
        button_signinLayout.setVerticalGroup(
            button_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_signup, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        signup_pane.add(button_signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 350, 40));

        gambarSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/daftar_libeeo.jpg"))); // NOI18N
        signup_pane.add(gambarSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(signup_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(signup_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cb_tampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tampilActionPerformed
        if (cb_tampil.isSelected()) {
            tf_password.setEchoChar((char)0);
        }else{
            tf_password.setEchoChar('*');
        }
    }//GEN-LAST:event_cb_tampilActionPerformed

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        // TODO add your handling code here:
        new FrontView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backMouseClicked

    private void button_signinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_signinMouseClicked
        // TODO add your handling code here:
        if (tf_nama.getText().equals("") 
            || tf_nim.getText().equals("") 
            || tf_email.getText().equals("") 
            || tf_nohp.getText().equals("") 
            || tf_password.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "data masih kosong");
        }else{
            try {
                String query = "INSERT INTO user"
                    + "(username,nim,email,nohp,password,role) "
                    + "VALUES (?, ? ,?, ?, ?, ?)";
                ps = conn.prepareStatement(query);
                ps.setString(1, tf_nama.getText());
                ps.setString(2, tf_nim.getText());
                ps.setString(3, tf_email.getText());
                ps.setString(4, tf_nohp.getText());
                ps.setString(5, tf_password.getText());
                ps.setString(6, "2");
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "berhasil register");
                Login lg = new Login();
                lg.setVisible(true);
                this.dispose();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, "Eror "+e.getMessage());
            }
        }
    }//GEN-LAST:event_button_signinMouseClicked

    private void button_signinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_signinMouseEntered
        // TODO add your handling code here:
        button_signin.setBackground(new Color(1,193,198));
        btn_signup.setForeground(Color.white);
    }//GEN-LAST:event_button_signinMouseEntered

    private void button_signinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_signinMouseExited
        // TODO add your handling code here:1,193,198
        button_signin.setBackground(Color.white);
        btn_signup.setForeground(new Color(1,193,198));
    }//GEN-LAST:event_button_signinMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_back;
    private javax.swing.JLabel btn_signup;
    private javax.swing.JPanel button_signin;
    private javax.swing.JCheckBox cb_tampil;
    private javax.swing.JLabel gambarSignup;
    private javax.swing.JPanel signup_pane;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JTextField tf_nim;
    private javax.swing.JTextField tf_nohp;
    private javax.swing.JPasswordField tf_password;
    // End of variables declaration//GEN-END:variables
}
